feat: support truncate long/double to int/float with option
NVIDIA/TRTorch pull request #407
Opened 2021-03-19 07:21 UTC by inocsin

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant and/or add your own.

- New feature (non-breaking change which adds functionality)
Support truncate long/double to int/float with option, add CompileSpec support
Please close the previous issue https://github.com/NVIDIA/TRTorch/pull/322

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes

2021-03-19 07:25 UTC, inocsin commented
@peri044 please review this PR

2021-03-19 08:58 UTC, peri044 requested changes
You have to add this flag on the python api side as well. Here are the locations

1) https://github.com/NVIDIA/TRTorch/blob/master/py/trtorch/csrc/trtorch_py.cpp#L234
2) https://github.com/NVIDIA/TRTorch/blob/740eb54055d73b10d216c835419acf6ee2e58d31/py/trtorch/csrc/tensorrt_classes.cpp#L95

3) https://github.com/NVIDIA/TRTorch/blob/740eb54055d73b10d216c835419acf6ee2e58d31/py/trtorch/csrc/tensorrt_classes.h#L90

4) https://github.com/NVIDIA/TRTorch/blob/740eb54055d73b10d216c835419acf6ee2e58d31/py/trtorch/csrc/register_tensorrt_classes.cpp#L39

2021-03-19 08:58 UTC, peri044 commented on core/conversion/var/Var.cpp
> +      LOG_WARNING("Truncate kLong to kInt for IValue");
Warning: Truncating weight (constant in the graph) from kLong to kInt to indicate that only constants are affected.

2021-03-19 08:58 UTC, peri044 commented on core/conversion/var/Var.cpp
> +      LOG_WARNING("Truncate kDouble to kFloat for IValue");
Same here as well w.r.t warning message

2021-03-19 17:39 UTC, narendasan commented on core/conversion/var/Var.cpp
> +    auto tensor = ptr_.ivalue->toTensor();
We should also check these cases if the setting is not enable to give users a hint to turn on truncating

2021-03-22 16:11 UTC, narendasan commented on core/conversion/var/Var.cpp
> +      TRTORCH_CHECK(0, "Unable to freeze tensor of type kLong/kDouble into constant layer, try to compile model with truncate_long_and_double ON");
Lets just call the types: Int32, Int64, Float64, Float32 throughout the warning messages

2021-03-22 16:11 UTC, narendasan commented on core/conversion/var/Var.cpp
> +      TRTORCH_CHECK(0, "Unable to freeze tensor of type kLong/kDouble into constant layer, try to compile model with truncate_long_and_double ON");
You can use `TRTORCH_THROW_ERROR` here

2021-03-22 16:27 UTC, peri044 commented on core/conversion/var/Var.cpp
> +      LOG_WARNING("Warning: Truncating weight (constant in the graph) from kLong to kInt to indicate that only constants are affected.");
@inocsin You can remove "to indicate that only constants are affected." This was just a message for you

2021-03-23 21:33 UTC, narendasan reviewed
Mostly looks good to go, one comment and resolve comments

2021-03-23 21:33 UTC, narendasan commented on core/conversion/var/Var.cpp
> +      LOG_WARNING("Warning: Truncating weight (constant in the graph) from Float64 to Float32.");
You dont need to say warning, the logging system will add that for you

2021-03-25 19:33 UTC, merged