Add instance norm
NVIDIA/TRTorch pull request #573
Opened 2021-08-11 16:03 UTC by zsef123

# Description

Add `InstanceNorm` using[TensorRT InstanceNormalizationPlugin](https://github.com/NVIDIA/TensorRT/tree/master/plugin/instanceNormalizationPlugin) and implementation of BatchNorm

Fixes #210 

Also I checked #285 
But this PR not supported TensorRT 8++
And it's a little different from mine.

1. default beta value, BN and #285  set to 1 but I think that must be 0
2. type of eps, float is right type. And also my env, double occurs error.
3. I called TensorRT directly not modifying other context (follows `gelu`)

## Type of change

Please delete options that are not relevant and/or add your own.

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes

2021-08-12 03:21 UTC, zsef123 commented
@narendasan passed DCO

2021-08-12 19:35 UTC, narendasan commented
@zsef123 Thanks for the contribution! Can you rebase your branch? Changes look mostly fine, once you rebase, I will run the tests and we should be good to go

2021-08-13 01:56 UTC, zsef123 commented
> @zsef123 Thanks for the contribution! Can you rebase your branch? Changes look mostly fine, once you rebase, I will run the tests and we should be good to go

Checked!!

2021-08-17 23:35 UTC, narendasan requested changes

2021-08-17 23:35 UTC, narendasan commented on core/conversion/converters/impl/batch_norm.cpp
> +              LOG_DEBUG("Scales : " <<    );
I think you are missing the `scales`  here. Its causing a compilation error

2021-08-18 22:02 UTC, narendasan commented
I am getting test failures for Converters.ATenInstanceNormRunningStatsConvertsCorrectly where the TRT implementation returns NaN. Using TRT8

2021-08-19 17:41 UTC, zsef123 commented
@narendasan  Sorry for missed.

Several problems were mixed. All of them were test cases.
1. range of `running_mean` and `running_var`
In testcase, cause overflow when calculate `gamma` and `bias`.
So changed `randn` -> `ones`, `zeros`. It is default value of `instance_norm`

2. not clone parameters in test case
fixed

And changes
1. changed device
It is not bug, but I just follows `batch_norm`
Changed `cpu` to `cuda` when the `track_running_stats==True`

2. readable graph in test

P.S.
I had a hard time creating a new docker environment.
Any plans for a distribution with NGC 21.07?

2021-08-20 05:46 UTC, narendasan commented
@zsef123 check #578 for a 21.07 container. It uses a version of Pytorch slightly newer than 1.9 but other than that should work

2021-08-20 21:04 UTC, narendasan approved these changes
Cool, tests pass, LGTM

2021-08-20 21:22 UTC, merged